{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- toYaml .Values.clusterIssuer.spec | nindent 2 }}
{{- end }}
