apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-vault-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv-secret
    kind: ClusterSecretStore
  target:
    name: argocd-vault-oidc
    creationPolicy: Owner
  data:
  - secretKey: clientId
    remoteRef:
      key: secret/data/local/argocd-vault-oidc
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: secret/data/local/argocd-vault-oidc
      property: clientSecret