apiVersion: v2
name: external-secrets-infrastructure
description: External Secrets Operator for Vault integration
type: application
version: 0.1.0
appVersion: "0.9.11"

dependencies:
  - name: external-secrets
    version: 0.9.11
    repository: https://charts.external-secrets.io