{{- if .Values.vaultSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.vaultSecretStore.name }}
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  provider:
    vault:
      server: {{ .Values.vaultSecretStore.vaultServer | quote }}
      path: {{ .Values.vaultSecretStore.vaultPath | quote }}
      version: {{ .Values.vaultSecretStore.vaultVersion | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vaultSecretStore.tokenSecret.name | quote }}
          key: {{ .Values.vaultSecretStore.tokenSecret.key | quote }}
---
{{- if .Values.vaultSecretStore.tokenSecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vaultSecretStore.tokenSecret.name }}
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.vaultSecretStore.tokenSecret.key }}: {{ .Values.vaultSecretStore.tokenSecret.value | b64enc }}
{{- end }}
{{- end }}