apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv-secret
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: secret/data/{{ .Values.environment }}/postgresql
      property: postgres-password
  - secretKey: password
    remoteRef:
      key: secret/data/{{ .Values.environment }}/postgresql
      property: password