apiVersion: v2
name: cert-manager-infrastructure
description: cert-manager setup for automatic certificate management
type: application
version: 0.1.0
appVersion: "1.13.0"

dependencies:
  - name: cert-manager
    version: v1.13.0
    repository: https://charts.jetstack.io