# Environment for External Secret templating
environment: local

postgresql:
  auth:
    existingSecret: "postgresql-credentials"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
    username: "postgres"
    database: "aircast_local"
  
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "standard"
    
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  
  metrics:
    enabled: false