# Environment for External Secret templating
environment: prod

postgresql:
  auth:
    existingSecret: "postgresql-credentials"
    secretKeys:
      adminPasswordKey: "POSTGRES_PASSWORD"
      userPasswordKey: "USER_PASSWORD"
    username: "postgres"
    database: "aircast_prod"
  
  primary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "gp2"
    
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
  
  metrics:
    enabled: true
    
  backup:
    enabled: true