apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - postgresql.yaml

commonLabels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/managed-by: argocd