apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.12.10
    helm:
      values: |
        auth:
          existingSecret: "postgresql-credentials"
          secretKeys:
            adminPasswordKey: "postgres-password"
            userPasswordKey: "password"
          username: "postgres"
          database: "aircast_local"  # Will be patched per environment
        
        primary:
          persistence:
            enabled: true
            size: 1Gi  # Will be patched per environment
            storageClass: "standard"  # Will be patched per environment
          
          resources:
            requests:
              memory: "256Mi"  # Will be patched per environment
              cpu: "250m"
            limits:
              memory: "512Mi"  # Will be patched per environment
              cpu: "500m"
        
        metrics:
          enabled: false  # Will be patched per environment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10